version: '2'
services:
  open:
    build: ./open
    image: open
    container_name: open
    hostname: open #optional
    ports:
      - 8080:80
      - 4242:4242
  data:
    build: ./data
    image: data
    container_name: data
    hostname: data #optional
    ports:
      - 8084:84
  dark:
    build: ./dark
    image: dark
    container_name: dark
    hostname: dark #optional
